version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/functions/itsmhelper/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"